codecov:
  branch: develop
  require_ci_to_pass: yes

ignore:
  - "source/stb_*.h"

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true