if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(ARCH_SUFFIX "-64")
else()
    set(ARCH_SUFFIX "")
endif()
if(MSVC OR MINGW)
    set(GLES_SDK_INCLUDE_PATH ${CMAKE_SOURCE_DIR}/thirdparty/gles_amd/include)
    set(GLES_SDK_EGL_LIBRARY ${CMAKE_SOURCE_DIR}/thirdparty/gles_amd/x86${ARCH_SUFFIX})
endif()

find_path(EGL_INCLUDE_DIR NAMES EGL/egl.h PATHS ${GLES_SDK_INCLUDE_PATH} )
if(EMSCRIPTEN)
    set(EGL_LIBRARY EGL)
else()
    find_library(EGL_LIBRARY NAMES egl EGL libEGL PATHS ${GLES_SDK_EGL_LIBRARY})
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(EGL DEFAULT_MSG EGL_LIBRARY EGL_INCLUDE_DIR)