find_path(GLES2_INCLUDE_DIR NAMES GLES2/GLES2.h)
find_library(GLES2_LIBRARY NAMES GLES2 GLES2)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GLES2 DEFAULT_MSG GLES2_LIBRARY GLES2_INCLUDE_DIR)