name: ci-tools

on: [push]

jobs:
  test:
    name: Run ci-tools on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Init git submodules
      run: git submodule update --init --recursive

    - name: Install CMake
      run: python ci-tools/install_cmake.py

    - name: Run CTest and push to CDash
      run: python ci-tools/run_ctest.py
