name: build and run tests
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  linux:
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.compiler }}
    strategy:
      matrix:
        include:
        - os: ubuntu-20.04
          compiler: gcc-9
        - os: ubuntu-20.04
          compiler: gcc-10
        - os: ubuntu-20.04
          compiler: clang-10
        - os: ubuntu-20.04
          compiler: clang-11
        - os: ubuntu-20.04
          compiler: clang-12
        - os: ubuntu-18.04
          compiler: gcc-7
        - os: ubuntu-18.04
          compiler: clang-9
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: dependencies
      run: sudo apt-get update && sudo apt-get install -yq ninja-build cppcheck flawfinder binutils-gold libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev libwayland-dev libxcb1-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-randr0-dev libxcb-util0-dev
    - name: install cmake
      run: python ci-tools/install_cmake.py
    - name: run ctest
      run: python ci-tools/run_ctest.py
  macos:
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.compiler }}
    strategy:
      matrix:
        include:
        - os: macos-10.15
          compiler: clang-12
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: dependencies
      run: brew update && brew install ninja cppcheck flawfinder
    - name: install cmake
      run: python ci-tools/install_cmake.py
    - name: run ctest
      run: python ci-tools/run_ctest.py