name: build and run tests
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-10.15]
        include:
          - os: ubuntu-20.04
            compiler: [gcc-9, gcc-10, clang-10, clang-11, clang-12]
          - os: ubuntu-18.04
            compiler: [gcc-7, clang-9]
          - os: macos-10.15
            compiler: clang-12
    env:
      CC: ${{ matrix.compiler }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: dependencies
      run: sudo apt-get update && sudo apt-get install -yq ninja-build cppcheck flawfinder binutils-gold libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev libwayland-dev libxcb1-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-randr0-dev libxcb-util0-dev
    - name: install cmake
      run: python ci-tools/install_cmake.py
    - name: run ctest
      run: python ci-tools/run_ctest.py